Add IO_MEM code for reference
Release Notes:
(a)dht11km.c
	fatal error: mach/hardware.h:
        No such file or directory
(b)dht11.c
        The dht11.c's driver calculation doesn't
	work.
(c)mcp3008
	testing from user space failed
(d)rpi.c,blink.c
	user space using the memory mapping to driect
	access the register to control
Detailed Notes:
- Problem : DHT11 snesor driver, MCP3008 platform
- RootCause : Mutex/ Spinlock Free
- Author :Polin Chen
- Build :
        (1)Kernel(Makefie, Cross Compiler, configuration)
                export ARCH=arm
                export CROSS_COMPILE=/home/paul/opt/gcc-raspberry-pi\
                /arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64\
                /bin/arm-linux-gnueabihf-
	(2)User Space for testing
Testing Preformed:
	(a)Figure how to implement the MCP3008 driver
	(b)the Driver of dht11.c's data doesn't workm need to fix.
	(c)dht11km.c(spinlock) compile error
How to Test :
        RP3 Using the ssh
        (a)Rp3_Pi pin
		(1)pin6  GND
		(2)pin8  UART-TX
		(3)pin10 UART-RX